version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - posturex_pgdata:/var/lib/postgresql/data
    restart: always
    env_file:
      - .env

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    volumes:
      - minio_data:/data
      - ./minio-setup.sh:/usr/bin/minio-setup.sh
    entrypoint: >
      sh -c "
        /usr/bin/minio server /data --console-address ':${MINIO_CONSOLE_PORT}' &
        sleep 10 &&
        chmod +x /usr/bin/minio-setup.sh &&
        /usr/bin/minio-setup.sh &&
        fg
      "
    restart: always
    env_file:
      - .env

  flask-app:
    build:
      context: .
    container_name: backend
    depends_on:
      - postgres
      - minio
    ports:
      - "${FLASK_PORT}:5000"
    volumes:
      - .:/app
    restart: always
    env_file:
      - .env

volumes:
  posturex_pgdata:
  minio_data:
