version: "3.8"
services:
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    container_name: minio
    ports:
      - "9000:9000"  # MinIO API
      - "9001:9001"  # MinIO Console
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=POSTUREX
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

  flask-app:
    build:
      context: .
    container_name: flask-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MINIO_ENDPOINT=minio:9000  # Override for Docker networking
    depends_on:
      minio:
        condition: service_healthy

volumes:
  minio-data:
